// <auto-generated />
namespace mPOS.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class aspmembershipmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspmembershipmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202005160647101_asp-membership-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
